### ISSUE TITLE
Incorrectly creating output layer relative to output image size

### ISSUE THREAD

**Issue by cse84** [Nenotriple/gimp_upscale#1]
I'm using GIMP 2.10.34 on Windows 10 and tried to upscale 2 images using this plugin. Unfortunately for one of the images the output was not the upscaled image, but only a fraction of it. For the image where upscaling worked, the result seemed to appear in 3 steps: First the image was resized to the output size, then the active layer was resized to that same size, then the upscaled image was copied into that layer. But for the second image, what instead happened was: the image is resized to the output size, then the active layer is NOT resized, then the top-left portion of the upscaled image was copied into the active layer. Thus in the end I could see only 1/4 of what I wanted for 2x superresolution, or 1/16 for 4x superresolution. I tried using superresolution on a 90° rotated input (because I thought that the aspect ratio might be the reason for the bug), but I still only got the top left corner.

I can work around the bug by copy/pasting the image into the top left corner of a much larger image, but that's a pain in the rear and will probably lead to out-of-memory errors for larger images.

I can attach screenshots if needed.

**Comment by Nenotriple** [comment]
I've been unable to reproduce this.

You may have some luck by selecting the entire layer and running the plug-in with the option `Upscale Input > From Selection`, as it works slightly different.

---

I've created a test version if you want to try that.

The normal release directly inserts the resized upscaled layer into the image, while this version creates a new empty layer and pastes the upscaled content into it.

Extract `ai_upscale_resrgan.py` to the same folder as where you installed/cloned the plug-in, replacing the orginal.
[ai_upscale_resrgan.zip](https://github.com/user-attachments/files/17535405/ai_upscale_resrgan.zip)

When testing, make sure you're using the option `Upscale Input > From Layer`.

**Comment by Nenotriple** [comment]
If this issue persists in v1.01+ please re-open the issue.
