### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Zhincore** [Nenotriple/gimp_upscale#2]
Hey, I'm interested in testing for Linux! I'd love to use this plugin on Debian

**Comment by Nenotriple** [comment]
Ok 👍 

I've created a separate branch `linux_test` with changes that should support Linux systems, I've also included the Linux version of RESRGAN.

You can pull the branch yourself, or download the pre-release from here https://github.com/Nenotriple/gimp_upscale/releases/tag/v1.03b

Please let me know how it works!

**Comment by Zhincore** [comment]
Amazing, I got it to work, thank you!

I had to put `#!/usr/bin/env python` as the very first line of the python file, otherwise the plugin wouldn't load.

Also I had to use <https://github.com/TasMania17/Gimp-Appimages-Made-From-Debs> because my GIMP installation doesn't support Python on it's own.

Also, just for documentation, the path for plug-ins on linux is `/home/<user>/.config/GIMP/2.10/plug-ins/`.

**Comment by Nenotriple** [comment]
I'm glad you got it working.

I didn't realize GIMP for Linux doesn't generally ship with Python, that does make the setup a little more involved. Maybe the script could be re-written in GIMPs *(archaic)* built-in language sometime. 

Maybe it's easier to direct Linux users to the official `Flatpack` version of GIMP where it could be more straightforward to set GIMP up with Python support.

I could direct people to that specific repo with the pre-built appimage, but that doesn't seem like the best approach for everyone.

I don't want to give bad advice, or send people on a goose chase, especially if I don't really know much about the environment. Maybe just a couple helpful links for Linux setup, and let people decide what seems easy for them? I'd really like your input here, especially about the flatpack.

**Comment by Zhincore** [comment]
I like your thinking! From what I understand future version of Debian and other distributions like Arch have a `gimp-python` as installable package, my version doesn't. That would be the best solution for most users.
Otherwise giving links to flatpack and appimage and let the user decide sounds good to me :thinking:
